export const TEXT = {
    'Dashboard_Title': 'Automated Assistant',
    'Dashboard_Subtitle': 'Let the AI assistant help you discover any signs of bladder cancer',
    'Dashboard_Button': 'Quick Analysis',
    'Navbar_Register': 'Register',
    'Navbar_Login': 'Login',
    'Analyse_Button': 'Analyse',
    'Analyse_Text': 'Please upload a NRRD image to be analyzed',
    'Analyse_Text_NotLoggedIn': "Please upload a NRRD image to be analyzed. <br/><br/> The analysis result will not be saved unless you login into your account or create one",
    'UploadedImage_Text': "Uploaded Image",
    "Email_Required": "Email is required",
    "Email_Invalid": "Not a valid email address",
    "Password_Required": "Password is required",
    "Password_MinLength": "Password should have at least 6 characters",
    "Password_NotMatch": "Passwords do not match",
    "Download_Archive": "Download PNG Archive",
    "Loading_Text": "This may take a minute...",
    "Upload_Image": "Select or drop image",
    "History": "History",
    "SignOut": "Sign Out",
    "Analysis_History": "Analysis History",
    "Error_History": "An error has occured and the history cannot be displayed at the moment",
    "No_History": "The history is currently empty because no analysis has been performed"
};