# Generated by Django 3.1.2 on 2020-10-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostateHelper', '0003_auto_20201031_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='confidence',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='pathToProcessed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
