# Generated by Django 3.1.2 on 2020-11-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prostateHelper', '0004_auto_20201031_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pathToProcessed',
            new_name='processed',
        ),
    ]
